<a href="https://colab.research.google.com/github/VannisaLaowongkot/Road-Accident-Risk-Prediction-Project/blob/main/Accidents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
url =  "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/4d919e5b-aa06-4fe4-8a13-5571747a1254/download/accident2019.csv"
df = pd.read_csv(url)
df.head()

/tmp/ipykernel_1074/1664995658.py:3: DtypeWarning: Columns (1,2,3,4,5,6,8,9,10,11,12,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
0,2019.0,1/1/2019,0:00,2/1/2019,6:11,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวัง...,4.00,ลพบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,2.0,แจ่มใส,14.959105,100.873463
1,2019.0,1/1/2019,0:03,20/2/2020,13:48,กรมทางหลวง,เดชอุดม - อุบลราชธานี,419.77,อุบลราชธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,2.0,แจ่มใส,15.210738,104.862689
2,2019.0,1/1/2019,0:05,1/1/2019,10:35,กรมทางหลวง,ปราณบุรี - ปากน้ำปราณ,1.70,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางโค้งกว้าง+ที่ลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง),2.0,1.0,0.0,แจ่มใส,12.374259,99.907949
3,2019.0,1/1/2019,0:20,2/1/2019,5:12,กรมทางหลวงชนบท,เชื่อมทางหลวงหมายเลข 1013 (กม.ที่ 8+200) - บ้า...,1.88,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,1.0,แจ่มใส,18.601721,98.804204
4,2019.0,1/1/2019,0:25,4/1/2019,9:42,กรมทางหลวง,เกยไชย - ศรีมงคล,68.80,นครสวรรค์,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,15.866389,100.590010

In [45]:
print(df.shape)

(40246, 19)

In [46]:
df.columns.to_list()

['ปีที่เกิดเหตุ',
 'วันที่เกิดเหตุ',
 'เวลา',
 'วันที่รายงาน',
 'เวลาที่รายงาน',
 'หน่วยงาน',
 'สายทาง',
 'ก.ม.',
 'จังหวัด',
 'รถคันที่ 1',
 'บริเวณที่เกิดเหตุ/ลักษณะทาง',
 'มูลเหตุสันนิษฐาน',
 'ลักษณะการเกิดอุบัติเหตุ',
 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)',
 'จำนวนผู้เสียชีวิต',
 'รวมจำนวนผู้บาดเจ็บ',
 'สภาพอากาศ',
 'LATITUDE',
 'LONGITUDE']

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40246 entries, 0 to 40245
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ปีที่เกิดเหตุ                     19194 non-null  float64
 1   วันที่เกิดเหตุ                    19194 non-null  object
 2   เวลา                              19194 non-null  object
 3   วันที่รายงาน                      19194 non-null  object
 4   เวลาที่รายงาน                     19194 non-null  object
 5   หน่วยงาน                          19194 non-null  object
 6   สายทาง                            19152 non-null  object
 7   ก.ม.                              19104 non-null  float64
 8   จังหวัด                           19183 non-null  object
 9   รถคันที่ 1                        19152 non-null  object
 10  บริเวณที่เกิดเหตุ/ลักษณะทาง       17659 non-null  object
 11  มูลเหตุสันนิษฐาน                  19137 non-null  object
 12  ลักษณะการเกิดอุบัติเหตุ           19144 non-null  object
 13  จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)  19194 non-null  float64
 14  จำนวนผู้เสียชีวิต                 19194 non-null  float64
 15  รวมจำนวนผู้บาดเจ็บ                19194 non-null  float64
 16  สภาพอากาศ                         19194 non-null  object
 17  LATITUDE                          19188 non-null  float64
 18  LONGITUDE                         19188 non-null  float64
dtypes: float64(7), object(12)
memory usage: 5.8+ MB

In [38]:
print(df.columns.tolist())

['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'วันที่รายงาน', 'เวลาที่รายงาน', 'หน่วยงาน', 'สายทาง', 'ก.ม.', 'จังหวัด', 'รถคันที่ 1', 'บริเวณที่เกิดเหตุ/ลักษณะทาง', 'มูลเหตุสันนิษฐาน', 'ลักษณะการเกิดอุบัติเหตุ', 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'สภาพอากาศ', 'LATITUDE', 'LONGITUDE']

In [48]:
missing_count = df.isnull().sum()
display(missing_count[missing_count > 0])

ปีที่เกิดเหตุ                       21052
วันที่เกิดเหตุ                      21052
เวลา                                21052
วันที่รายงาน                        21052
เวลาที่รายงาน                       21052
หน่วยงาน                            21052
สายทาง                              21094
ก.ม.                                21142
จังหวัด                             21063
รถคันที่ 1                          21094
บริเวณที่เกิดเหตุ/ลักษณะทาง         22587
มูลเหตุสันนิษฐาน                    21109
ลักษณะการเกิดอุบัติเหตุ             21102
จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)    21052
จำนวนผู้เสียชีวิต                   21052
รวมจำนวนผู้บาดเจ็บ                  21052
สภาพอากาศ                           21052
LATITUDE                            21058
LONGITUDE                           21058
dtype: int64

In [49]:
df.head(40246)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
0,2019.0,1/1/2019,0:00,2/1/2019,6:11,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวัง...,4.00,ลพบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,2.0,แจ่มใส,14.959105,100.873463
1,2019.0,1/1/2019,0:03,20/2/2020,13:48,กรมทางหลวง,เดชอุดม - อุบลราชธานี,419.77,อุบลราชธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,2.0,แจ่มใส,15.210738,104.862689
2,2019.0,1/1/2019,0:05,1/1/2019,10:35,กรมทางหลวง,ปราณบุรี - ปากน้ำปราณ,1.70,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางโค้งกว้าง+ที่ลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง),2.0,1.0,0.0,แจ่มใส,12.374259,99.907949
3,2019.0,1/1/2019,0:20,2/1/2019,5:12,กรมทางหลวงชนบท,เชื่อมทางหลวงหมายเลข 1013 (กม.ที่ 8+200) - บ้า...,1.88,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,1.0,แจ่มใส,18.601721,98.804204
4,2019.0,1/1/2019,0:25,4/1/2019,9:42,กรมทางหลวง,เกยไชย - ศรีมงคล,68.80,นครสวรรค์,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,15.866389,100.590010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df = df.dropna(how="all")
print("จำนวนแถวหลังลบ:", len(df))
display(df.tail())

จำนวนแถวหลังลบ: 19194

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
19189,2019.0,31/12/2019,23:30,19/2/2020,14:22,กรมทางหลวง,ทางเข้าสังขละบุรี,1.25,กาญจนบุรี,รถปิคอัพบรรทุก 4 ล้อ,ทางโค้งกว้าง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,1.0,0.0,แจ่มใส,15.171119,98.462388
19190,2019.0,31/12/2019,23:35,1/1/2020,0:47,กรมทางหลวง,ปากน้ำกระบี่ - เขาทอง,14.66,กระบี่,รถจักรยานยนต์,NaN,ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน,ชนท้าย,2.0,0.0,2.0,แจ่มใส,8.092608,98.811692
19191,2019.0,31/12/2019,23:40,1/1/2020,6:44,กรมทางหลวงชนบท,ถนนสมโภชเชียงใหม่ 700 ปี,5.60,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,ชนท้าย,2.0,1.0,0.0,แจ่มใส,18.829234,99.006029
19192,2019.0,31/12/2019,23:40,1/1/2020,9:29,กรมทางหลวง,กระบุรี - หงาว,601.12,ระนอง,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,2.0,0.0,มีหมอก/ควัน/ฝุ่น,9.939225,98.633500
19193,2019.0,31/12/2019,23:45,3/1/2020,11:01,กรมทางหลวง,บางพลี - บางบ่อ,22.00,สมุทรปราการ,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนสิ่งกีดขวาง (บนผิวจราจร),2.0,1.0,0.0,แจ่มใส,13.588040,100.788317