<a href="https://colab.research.google.com/github/VannisaLaowongkot/Road-Accident-Risk-Prediction-Project/blob/main/Accidents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
url =  "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/4d919e5b-aa06-4fe4-8a13-5571747a1254/download/accident2019.csv"
df = pd.read_csv(url)
df.head()

/tmp/ipykernel_1074/1664995658.py:3: DtypeWarning: Columns (1,2,3,4,5,6,8,9,10,11,12,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
0,2019.0,1/1/2019,0:00,2/1/2019,6:11,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวัง...,4.00,ลพบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,2.0,แจ่มใส,14.959105,100.873463
1,2019.0,1/1/2019,0:03,20/2/2020,13:48,กรมทางหลวง,เดชอุดม - อุบลราชธานี,419.77,อุบลราชธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,2.0,แจ่มใส,15.210738,104.862689
2,2019.0,1/1/2019,0:05,1/1/2019,10:35,กรมทางหลวง,ปราณบุรี - ปากน้ำปราณ,1.70,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางโค้งกว้าง+ที่ลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง),2.0,1.0,0.0,แจ่มใส,12.374259,99.907949
3,2019.0,1/1/2019,0:20,2/1/2019,5:12,กรมทางหลวงชนบท,เชื่อมทางหลวงหมายเลข 1013 (กม.ที่ 8+200) - บ้า...,1.88,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,1.0,แจ่มใส,18.601721,98.804204
4,2019.0,1/1/2019,0:25,4/1/2019,9:42,กรมทางหลวง,เกยไชย - ศรีมงคล,68.80,นครสวรรค์,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,15.866389,100.590010

In [45]:
print(df.shape)

(40246, 19)

In [46]:
df.columns.to_list()

['ปีที่เกิดเหตุ',
 'วันที่เกิดเหตุ',
 'เวลา',
 'วันที่รายงาน',
 'เวลาที่รายงาน',
 'หน่วยงาน',
 'สายทาง',
 'ก.ม.',
 'จังหวัด',
 'รถคันที่ 1',
 'บริเวณที่เกิดเหตุ/ลักษณะทาง',
 'มูลเหตุสันนิษฐาน',
 'ลักษณะการเกิดอุบัติเหตุ',
 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)',
 'จำนวนผู้เสียชีวิต',
 'รวมจำนวนผู้บาดเจ็บ',
 'สภาพอากาศ',
 'LATITUDE',
 'LONGITUDE']

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40246 entries, 0 to 40245
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ปีที่เกิดเหตุ                     19194 non-null  float64
 1   วันที่เกิดเหตุ                    19194 non-null  object
 2   เวลา                              19194 non-null  object
 3   วันที่รายงาน                      19194 non-null  object
 4   เวลาที่รายงาน                     19194 non-null  object
 5   หน่วยงาน                          19194 non-null  object
 6   สายทาง                            19152 non-null  object
 7   ก.ม.                              19104 non-null  float64
 8   จังหวัด                           19183 non-null  object
 9   รถคันที่ 1                        19152 non-null  object
 10  บริเวณที่เกิดเหตุ/ลักษณะทาง       17659 non-null  object
 11  มูลเหตุสันนิษฐาน                  19137 non-null  object
 12  ลักษณะการเกิดอุบัติเหตุ           19144 non-null  object
 13  จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)  19194 non-null  float64
 14  จำนวนผู้เสียชีวิต                 19194 non-null  float64
 15  รวมจำนวนผู้บาดเจ็บ                19194 non-null  float64
 16  สภาพอากาศ                         19194 non-null  object
 17  LATITUDE                          19188 non-null  float64
 18  LONGITUDE                         19188 non-null  float64
dtypes: float64(7), object(12)
memory usage: 5.8+ MB

In [38]:
print(df.columns.tolist())

['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'วันที่รายงาน', 'เวลาที่รายงาน', 'หน่วยงาน', 'สายทาง', 'ก.ม.', 'จังหวัด', 'รถคันที่ 1', 'บริเวณที่เกิดเหตุ/ลักษณะทาง', 'มูลเหตุสันนิษฐาน', 'ลักษณะการเกิดอุบัติเหตุ', 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'สภาพอากาศ', 'LATITUDE', 'LONGITUDE']

In [48]:
missing_count = df.isnull().sum()
display(missing_count[missing_count > 0])

ปีที่เกิดเหตุ                       21052
วันที่เกิดเหตุ                      21052
เวลา                                21052
วันที่รายงาน                        21052
เวลาที่รายงาน                       21052
หน่วยงาน                            21052
สายทาง                              21094
ก.ม.                                21142
จังหวัด                             21063
รถคันที่ 1                          21094
บริเวณที่เกิดเหตุ/ลักษณะทาง         22587
มูลเหตุสันนิษฐาน                    21109
ลักษณะการเกิดอุบัติเหตุ             21102
จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)    21052
จำนวนผู้เสียชีวิต                   21052
รวมจำนวนผู้บาดเจ็บ                  21052
สภาพอากาศ                           21052
LATITUDE                            21058
LONGITUDE                           21058
dtype: int64

In [49]:
df.head(40246)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
0,2019.0,1/1/2019,0:00,2/1/2019,6:11,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวัง...,4.00,ลพบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,2.0,แจ่มใส,14.959105,100.873463
1,2019.0,1/1/2019,0:03,20/2/2020,13:48,กรมทางหลวง,เดชอุดม - อุบลราชธานี,419.77,อุบลราชธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,2.0,แจ่มใส,15.210738,104.862689
2,2019.0,1/1/2019,0:05,1/1/2019,10:35,กรมทางหลวง,ปราณบุรี - ปากน้ำปราณ,1.70,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางโค้งกว้าง+ที่ลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง),2.0,1.0,0.0,แจ่มใส,12.374259,99.907949
3,2019.0,1/1/2019,0:20,2/1/2019,5:12,กรมทางหลวงชนบท,เชื่อมทางหลวงหมายเลข 1013 (กม.ที่ 8+200) - บ้า...,1.88,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,1.0,แจ่มใส,18.601721,98.804204
4,2019.0,1/1/2019,0:25,4/1/2019,9:42,กรมทางหลวง,เกยไชย - ศรีมงคล,68.80,นครสวรรค์,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,15.866389,100.590010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df = df.dropna(how="all")
print("จำนวนแถวหลังลบ:", len(df))
display(df.tail())

จำนวนแถวหลังลบ: 19194

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
19189,2019.0,31/12/2019,23:30,19/2/2020,14:22,กรมทางหลวง,ทางเข้าสังขละบุรี,1.25,กาญจนบุรี,รถปิคอัพบรรทุก 4 ล้อ,ทางโค้งกว้าง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,1.0,0.0,แจ่มใส,15.171119,98.462388
19190,2019.0,31/12/2019,23:35,1/1/2020,0:47,กรมทางหลวง,ปากน้ำกระบี่ - เขาทอง,14.66,กระบี่,รถจักรยานยนต์,NaN,ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน,ชนท้าย,2.0,0.0,2.0,แจ่มใส,8.092608,98.811692
19191,2019.0,31/12/2019,23:40,1/1/2020,6:44,กรมทางหลวงชนบท,ถนนสมโภชเชียงใหม่ 700 ปี,5.60,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,ชนท้าย,2.0,1.0,0.0,แจ่มใส,18.829234,99.006029
19192,2019.0,31/12/2019,23:40,1/1/2020,9:29,กรมทางหลวง,กระบุรี - หงาว,601.12,ระนอง,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,2.0,0.0,มีหมอก/ควัน/ฝุ่น,9.939225,98.633500
19193,2019.0,31/12/2019,23:45,3/1/2020,11:01,กรมทางหลวง,บางพลี - บางบ่อ,22.00,สมุทรปราการ,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนสิ่งกีดขวาง (บนผิวจราจร),2.0,1.0,0.0,แจ่มใส,13.588040,100.788317

In [52]:
missing_count = df.isnull().sum()
display(missing_count[missing_count > 0].sort_values(ascending=False))

บริเวณที่เกิดเหตุ/ลักษณะทาง    1535
ก.ม.                             90
มูลเหตุสันนิษฐาน                 57
ลักษณะการเกิดอุบัติเหตุ          50
สายทาง                           42
รถคันที่ 1                       42
จังหวัด                          11
LATITUDE                          6
LONGITUDE                         6
dtype: int64

In [53]:
rows_with_missing = df[df.isnull().any(axis=1)]
display(rows_with_missing.head(10))

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
6,2019.0,1/1/2019,0:30,25/10/2019,14:25,กรมทางหลวง,ท่าทอง - สวนสมบูรณ์,65.850,ชุมพร,รถปิคอัพบรรทุก 4 ล้อ,NaN,ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน,ชนเป็นมุมบริเวณทางแยก,2.0,0.0,2.0,แจ่มใส,9.949354,99.063479
20,2019.0,1/1/2019,1:30,4/1/2019,11:56,กรมทางหลวง,ขุนตาน - อุโมงค์,508.365,ลำพูน,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,0.0,0.0,มีหมอก/ควัน/ฝุ่น,18.465851,99.149981
44,2019.0,1/1/2019,3:00,2/1/2019,22:31,กรมทางหลวง,เมืองภูเก็ต - กะทู้,1.148,ภูเก็ต,รถจักรยานยนต์,NaN,ขับรถเร็วเกินอัตรากำหนด,ชนท้าย,2.0,0.0,1.0,แจ่มใส,7.893418,98.365762
46,2019.0,1/1/2019,3:00,29/3/2019,8:22,กรมทางหลวง,ราษฎร์บูรณะ - พระสมุทรเจดีย์,21.600,สมุทรปราการ,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร,ชนเป็นมุมบริเวณทางแยก,2.0,0.0,0.0,แจ่มใส,13.594435,100.579662
47,2019.0,1/1/2019,3:05,1/1/2019,3:05,การทางพิเศษแห่งประเทศไทย,บางพลี-สุขสวัสดิ์,NaN,กรุงเทพมหานคร,NaN,อื่นๆ,NaN,NaN,1.0,0.0,1.0,แจ่มใส,13.790529,100.610702
51,2019.0,1/1/2019,3:20,20/2/2019,13:50,กรมทางหลวง,ทางเลี่ยงเมืองลพบุรี,5.350,ลพบุรี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,14.755132,100.650934
52,2019.0,1/1/2019,3:30,5/1/2019,11:00,กรมทางหลวง,แยกโพธารส - ท่ายาง,2.350,ชุมพร,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,1.0,แจ่มใส,10.486153,99.194186
53,2019.0,1/1/2019,3:30,9/10/2019,15:57,กรมทางหลวง,สองพี่น้อง - มะขามล้ม,11.600,สุพรรณบุรี,รถปิคอัพบรรทุก 4 ล้อ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,0.0,0.0,แจ่มใส,14.238329,100.042807
58,2019.0,1/1/2019,4:25,11/6/2019,9:32,กรมทางหลวง,ท่าชี - ถ้ำพรรณรา,225.532,สุราษฎร์ธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,ชนท้าย,2.0,0.0,3.0,แจ่มใส,8.629675,99.352289
81,2019.0,1/1/2019,5:42,1/1/2019,5:42,การทางพิเศษแห่งประเทศไทย,บางนา-ชลบุรี,NaN,กรุงเทพมหานคร,อื่นๆ,ทางตรง,NaN,NaN,1.0,0.0,0.0,แจ่มใส,13.790529,100.610702

In [69]:
df_clean = df.copy()
columns_to_drop = [
    "วันที่รายงาน",
    "เวลาที่รายงาน",
    "หน่วยงาน",
    "บริเวณที่เกิดเหตุ/ลักษณะทาง",
    "มูลเหตุสันนิษฐาน",
    "ลักษณะการเกิดอุบัติเหตุ",
    "สภาพอากาศ",
    "รถคันที่ 1"
    ]

df_clean = df_clean.drop(columns=columns_to_drop)
print("จำนวนแถวและคอลัมน์หลังลบ:", df_clean.shape)
print("คอลัมน์ที่เหลือ:")
print(df_clean.columns.tolist())

จำนวนแถวและคอลัมน์หลังลบ: (19194, 11)
คอลัมน์ที่เหลือ:
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'ก.ม.', 'จังหวัด', 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'LATITUDE', 'LONGITUDE']

In [70]:
missing_count = df_clean.isnull().sum()
display(missing_count[missing_count > 0].sort_values(ascending=False))

ก.ม.         90
สายทาง       42
จังหวัด      11
LATITUDE      6
LONGITUDE     6
dtype: int64

In [71]:
rows_with_missing_clean = df_clean[df.isnull().any(axis=1)]
display(rows_with_missing_clean.head(10))

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,ก.ม.,จังหวัด,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,LATITUDE,LONGITUDE
6,2019.0,1/1/2019,0:30,ท่าทอง - สวนสมบูรณ์,65.850,ชุมพร,2.0,0.0,2.0,9.949354,99.063479
20,2019.0,1/1/2019,1:30,ขุนตาน - อุโมงค์,508.365,ลำพูน,1.0,0.0,0.0,18.465851,99.149981
44,2019.0,1/1/2019,3:00,เมืองภูเก็ต - กะทู้,1.148,ภูเก็ต,2.0,0.0,1.0,7.893418,98.365762
46,2019.0,1/1/2019,3:00,ราษฎร์บูรณะ - พระสมุทรเจดีย์,21.600,สมุทรปราการ,2.0,0.0,0.0,13.594435,100.579662
47,2019.0,1/1/2019,3:05,บางพลี-สุขสวัสดิ์,NaN,กรุงเทพมหานคร,1.0,0.0,1.0,13.790529,100.610702
51,2019.0,1/1/2019,3:20,ทางเลี่ยงเมืองลพบุรี,5.350,ลพบุรี,1.0,0.0,0.0,14.755132,100.650934
52,2019.0,1/1/2019,3:30,แยกโพธารส - ท่ายาง,2.350,ชุมพร,1.0,0.0,1.0,10.486153,99.194186
53,2019.0,1/1/2019,3:30,สองพี่น้อง - มะขามล้ม,11.600,สุพรรณบุรี,1.0,0.0,0.0,14.238329,100.042807
58,2019.0,1/1/2019,4:25,ท่าชี - ถ้ำพรรณรา,225.532,สุราษฎร์ธานี,2.0,0.0,3.0,8.629675,99.352289
81,2019.0,1/1/2019,5:42,บางนา-ชลบุรี,NaN,กรุงเทพมหานคร,1.0,0.0,0.0,13.790529,100.610702

In [72]:
missing_latitude = df_clean[df_clean["LATITUDE"].isnull()]
display(missing_latitude)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,ก.ม.,จังหวัด,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,LATITUDE,LONGITUDE
501,2019.0,2/1/2019,21:30,แยกทางหลวงหมายเลข 9 (กม.ที่ 43+490) - อำเภอไทร...,3.00,NaN,2.0,0.0,2.0,NaN,NaN
7643,2019.0,7/5/2019,3:15,แยกทางหลวงหมายเลข 317 (กม.ที่ 10+100) - บ้านทุ...,4.95,NaN,1.0,0.0,0.0,NaN,NaN
8039,2019.0,15/5/2019,11:45,แยกทางหลวงหมายเลข 1 (กม.ที่ 123+400) - บ้านสองคอน,11.90,NaN,2.0,0.0,4.0,NaN,NaN
8044,2019.0,15/5/2019,13:50,แยกทางหลวงหมายเลข 416 (กม.ที่ 6+250) -บ้านคลอง...,3.10,NaN,2.0,0.0,2.0,NaN,NaN
11279,2019.0,1/8/2019,8:00,แยกทางหลวงหมายเลข 22 (กม.ที่ 235+225) - บ้านรา...,0.80,NaN,2.0,0.0,1.0,NaN,NaN
17957,2019.0,28/12/2019,2:30,แยกทางหลวงหมายเลข 2418 (กม.ที่ 21+600) - บ้านบ...,2.35,NaN,1.0,0.0,1.0,NaN,NaN

In [76]:
df_clean = df_clean.dropna(subset=["LATITUDE"])
missing_count = df_clean.isnull().sum()
display(missing_count[missing_count > 0].sort_values(ascending=False))

ก.ม.       90
สายทาง     42
จังหวัด     5
dtype: int64